// ⚠️  IMPORTANT: Replace this file with the one generated by:
//     flutterfire configure
//
// Steps:
//   1. Install FlutterFire CLI:  dart pub global activate flutterfire_cli
//   2. In your project root run: flutterfire configure
//   3. Select your Firebase project
//   4. The tool will generate this file automatically with YOUR project's values.
//
// The placeholder values below are for reference ONLY – they will NOT work.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Replace ALL values below with those from YOUR Firebase project ────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOxUXtO1x8fTmRali3-CzQF8Rmq9JISx4',
    appId: '1:1053341765297:android:de3ec6ac31a212c1bf9c90',
    messagingSenderId: '1053341765297',
    projectId: 'web-design-f08ce',
    storageBucket: 'web-design-f08ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwNunFHCWOvBevFRAxIUSywieqsND7r2c',
    appId: '1:1053341765297:ios:889dc0a7cd3e5263bf9c90',
    messagingSenderId: '1053341765297',
    projectId: 'web-design-f08ce',
    storageBucket: 'web-design-f08ce.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

}